### ISSUE TITLE
Question about the paper. Table 1

### ISSUE THREAD

**Issue by mountains-high** [zju-vipa/Fast-Datafree#7]
Good day,
Thank you for the great work.

I wanted to know in order to get 92.62% (on fast2) how many images were generated? 
Were the number of generated images the same as DeepInv, CMI, etc.? 

![image](https://user-images.githubusercontent.com/82306310/177091589-a1a4b477-e511-4615-8cf6-2de1635ca106.png)

Thank you.
Best

**Comment by Mo-Kanya** [comment]
~50k images were generated, and yes, it is the same for both DeepInversion and CMI. For nongenerative methods like DAFL, ZSKT, DFQ, the number is much larger due to differences in how they utilize generated sample.

**Comment by mountains-high** [comment]
Good day, 

Thank you very much for your kind response.
Good luck with your research~

**Comment by Mo-Kanya** [comment]
Hi,

I have corrected my old answer after rechecking the code. The number of generated images should be around 50k. 80k is actually the number of iterations.

As you can see from provided scripts, our experiments run 200 epochs, and a batch of images is generated in each epoch (in [synthesize()](https://github.com/zju-vipa/Fast-Datafree/blob/c1884872ba0c530e3f8c2538bacd4cc2915bad76/datafree/synthesis/fast_meta.py#L114)). By default, the "[synthesis_batch_size](https://github.com/zju-vipa/Fast-Datafree/blob/c1884872ba0c530e3f8c2538bacd4cc2915bad76/datafree/synthesis/fast_meta.py#L114)" takes the value of batch size, which is 256 in our case. 

Sorry for the mistake.

**Comment by Mo-Kanya** [comment]
Hi @mountains-high,

I have corrected my old answer after rechecking the code. The number of generated images should be around 50k. 80k is actually the number of iterations.

As you can see from provided scripts, our experiments run 200 epochs, and a batch of images is generated in each epoch (in [synthesize()](https://github.com/zju-vipa/Fast-Datafree/blob/c1884872ba0c530e3f8c2538bacd4cc2915bad76/datafree/synthesis/fast_meta.py#L114)). By default, the "[synthesis_batch_size](https://github.com/zju-vipa/Fast-Datafree/blob/c1884872ba0c530e3f8c2538bacd4cc2915bad76/datafree/synthesis/fast_meta.py#L114)" takes the value of batch size, which is 256 in our case. 

Sorry for the mistake.

**Comment by mountains-high** [comment]
Well received your message.

Thank you very much for your consideration and time. 
Thank you
